RNA = 'AUGGCACGCCUUACUUUAACCGUCACGACAGGGGUAUUACAGGCUCAGGCUAGUUUCAGAAUUGUUAUUUCCAUUAGAUUGUUCCCUGUUAGUCAUGUGGUGAUAUCGCGGCGUAGAUGUCAAGAGGACUGCUCUAUAUCUCUCAGGGCAGUGUGCAAACUGCCCCAUUUUGCUCUGACAAUCCUCAUUGGACAAUGUAUCUUAAUGUGUGGGCCCGACCAAAUGGGUUAUGGGUGUGCCCGCAAUUUCUCAACAGUACCACGAUCCACGGCAACUGACCUUAAGCCCCGGUCUCUCGUAUCGACUAAGACUGCUAGAGAUCUCAUUUGGUUGUUUACCUGCUCCCAGUUAGUCAGACCGGUUCCCGGGCGUUUCCAGCGAGCUCAUCAACGUGACCAAUCUAGCCCAAGGGACAAAGAGCCCGCAACUCUUAUAAGCGUAGCAAAUGAUGAUUCGCUCUGCGGCAUACGUGACACUGGAGAAGGGCUUAGGCCCCCUUCGGCAUGGGGAGAGGACGAGGCCGGAGCGUUACAGCGCGAGUCCACGGCGACCCUGUCCUUCCACAAUCUAAAUGGGAUAGCUUCUGACUAUGGUCCGAGAGAGGCUUGCCCUGGGGGUCUUAUUGUCAAAGGGCUAGAGACAUUAUCCCAGCGAUUUUCACACACCGUAUUACGCUCUCGCUAUAAAUCGAGAACUCGUAGUCGUCACGCAGACCGCACGAAUCCGAGCCUCGACCGCUGCCCCGGCGUUCUAGGUUUCGCUAGAAAGGAUCCGAAGUUUCACAGUGGGCGGGCCUACAAGUCCACUCUCGGAGGUGGGAAAAAAUCUAAUCCCCCCGCAGGUUGGCGAUUUGAUUCUAGGUCUGGUCUUAAAACUGGCGUUAUAGUACCGGUUAGUCUAAGCCUCGCGGAGUGUUCCAGGCGUUUAGACUUGAGAUCACAGGAGUCCCUUCAUAGCUGGGAAAAUAUGUUAUCGCCCUUGCCGUGCCAUUCAUCACCAUGUAGAAGUGCGCACUCAAGUAAAAUGGCAACGCUUGACCAGGGCAAUGCCGUAAGACUCCAUAUUCUUAGCAGGCUCGAGACACAAUUAGAUCAAACUUCCGUUCGGCCUAUCAUUGCGAUCCUCGAUAAACCAAACAUGGUACGCCGGUGGUUGGGCGGAAUCCCUGAGUUGAUUUGGAGCAGCACGAAUCAACACAUUCUUUGUCUCCCAAAUUGCAGCCUCAGUAUCCGGGAAAGGUUAGGGAUAACGUCGGUAUCACACGAGGCGAACACCCUUAGUGUCCUGCAUGACUUUUCACGGAGCCAACGUCCUUCCAUUUCGGGGUCUUUUUCUCCAGCACGAGUCGGUCUCUUACGUAAUGUAUCGAUACACCGCCAUAUACUAGGUAUACGGUUCCCCACGUUUGUGUUUGACAGAGGUCGGGAUCGGCCUGCUUUGGAUGACCUGGUACUGUGGUCUGACUCGUUCUCGGGCGCAAUCCCUAGCAGGCUCAACAGCCCCUACGUAAAUGCAAACCCCCGACGCGCCACCGCCCCUAGCAGAGGCAGCGAGUUGGUAUUAGAGUUUUGUACUAGUCAUAUAUACCGGUUGGGAGGCUACAGAGGGUGGCUGGACACUACCGACACGUCAAUCCGCCAAGCCCCAAUUAUUACGGGCUCUUCUAAAGUGCAUCCAACAUACAUGGCCAAAGCACGCCUCGGAGCAUCUCGGCCCGAGCCCAUUUGGGUCCCCCAGACUCUUAUAUUGACGCGAGCGAACGGGCACGCAAGUCCUCGUCUUAGCUGCGGUAGUAAUCCGGAGUAUCGUACCAGACCGAUCAAGGGAGUCUUCCGACGCAAACUAAUACCCUCAGUCGUCUAUUCGAAGCCGCACGAAUGGAAGUUCUUAGGCCUCAUUACGCAGGUCUCAAAGGUCAAAGGCCAUCAGAAAAUUAAUGUCAGUGAAAUUGAAAAGACCGGCGACAGUUUGACGAUAGACAAACUCAGUCCCUGCAUAGCCAACACAGCGUCUAGUAAGGAGGUUAGGUUGCAAGAAAAAGCAAAGUAUCCUCCGCGUGGCCACCUGAUUGAUGCCACGUCUAACCCGGGGAUAUGUCAUGGGGUGUUAGUCCAGAUCAUAUCAUUUGAUUUCAAGUUCGGAGCUUACAUGCGGAAAACUGGUCGUGGUUUCAGGCAUCCCUGCUUUCAUCCUUGUAGAACCCUCCUGGCUACACACGCAGAAGAGAAGCGUCCCCACUACUCGGCGGCGCUGCGACGGAAGGUGGUUGCGGCUAACCAAACAACACUCCUGCAACGAUACACAGAAAUGGCGCCUUGGGAAACUGCGAAGCGUGACCACAUAGACGAAUCGGUGAUGGUCACUUUCGUGGUGUUGGACGAAAUAUCCCCUACGUUGAACUGUUUGCAGCCCUGUUUACGCCUCAUUGCUAUCAAUACGACUAUCACGGAAGCAGGUACCCAGGGGCGGGCCAUACGGAUUGCUAUGUUAACAAAAAGGUUCGUAUAUUCACGUUGCGAAGUGGGGGUUCAUCCAUGCUAUCAGAAAGCACUAGGAAGGAUGGUCCUCAAGUGGUCUGAACGUGGGCGUUGCGAAAUGUAUCGACUCGCCAACAAAUUGCCUACUCCAACUAAGCGAACCCAGGGAAACUUGGUCGGGCAGCAGCUAGUUGUACUAGUUAGUAGGGUACGCGGGAGCACAUGUUGUCGCAUUAAUAAACGGUUCGAGAGAUCAACGGGCGUUCCAACAUCAUCUGUUCCUGACUUCCUCCCGUGGUCCUGGCUAACGCACGACCCACGAAGAGUAAAGUCCGAGUUGAUACAAAUUGCUAAUGUUAUACAGAUACCAUCCUUCUGCUCGCCCUUAUGCCUUAUACAAGUAUAUUAUAGUAUGCUUUCUCAAUUAGCAAGUUUGCUGUUUCCAAGUCUCACUGAUCGUUGUUUUACCGUGAGUGAGCGCACUGCAAUUGAUGCAAGUACAAUGUGGGAAUAUAGUAAUCUAAGGGCCCGCUCGUAUGACCCUCUUUGGGCAAGCGUCUCCAUGCUACAUGUCAUAAAAUCCGAAUACAAUUCCGUGUUUGCAUACCAGUUCAUCAUGUCUCGGCCGUAUUAUGCUGGAACUUCUGGGCGUUCCUUAAUUAUUCGAACAAGUCUCAUUUGGUCAAUCUUCCGUACUUAUAACUACCAGGAGGUUUCCGAACUACUGGGUGAUUCAGGUACUGCUUUCGCUCAAAGUCAUAACGUAACUGCAAUUGCUAAGCGCGAUAUCAAGAACGUGUUCAGUCGAGGCCAAUGCAAGCAAUAUUCCCUGUCUGAUUCCGAGUGCAGGGACUUGUGCAGGUUUCUAUUCAAUAGUUUUAGUUAUGGGCGUACCACCAGCUGUGUAGAUCGGUUGCAGACGAACUCCGGCCCGCUCGGCGAAUUCGAGAAGAGCACUGACAGAAAAGAAAAGGGUAUGAGAUUUCGCGUUUUGAACUCUGGCGCCAACAACCUCGUCGGCAUAAGGACGACGUAUUUACUAUCUCUCCCCAUGGCCUUAGACAAUUCUUUUACUCAGUGCAAAACUCAACACGGAUCAGCACCUGCAUUACUGGACCUAGAGCCCCGAUAUCCGCCUCCUGUAACUGGGCGACUAGGCGGUACGCGAGUACCGUCGCCCCCUUGUGAACGCGAAGCUUCAGAUAUAGAUAGACUGACCGGCACUAUCACCGCAAUACCUUACAGAAAGUUAAGCUGUCUUUGGGAGUAUUCCCCCCCAUACACAACCUUAGAAUUCAAUCGGGGGAGGAGUAAGCAACGUAAAGUAUUGUCAUGGAAAGUCGUGGUGGCCUGCGCCGGACGCACACACCUGAUCCAAACCGUUUUGGUACGGUGGGCGAUAUGGGUUCGUACACAACGGCGACUCGCAAGGACGGGCUCCUCCGCGAUGCAAUCACAAUCGCUUACGAAGGCCCAUGCGCCGAGUGAACCAUACGUCAAUGGUUCCGAGAGGACUGACCUCAAUCAGGUGACGGCCCAGAUACGUUUUGAUGACGGAGUGAUCGUGUCGGAUAGAACCUUGAUCAAGGUCCAUUCUAAAAGGAUAUCUUUAUCGCGUCCGAUGAGACCCUGCUAUUCACGAGGAUUUUUGACUGGGCCUAGAGGGCCUGUGAUGGUAAAACCUUGCUCCAAUAGCGCCGCGAACAUAGCAGAACUCCUUAAGGAAGUCACCGCUGAUCGUUUGCGCCUACCCUGUUGCUCCUCAACAGAGCGGACGUCUGUGGCUUGUCAACGCGACCGUUCUCAGGGCCGAGCAGCGUGUUACCUGUACCCGGUCACACUGAGUCUGGUGAGUUUGAGUAACGUAUCCCCCUCGCGCGCGCCCAUCCACGAAACAAUCGCGCAAUACGCUACUCGGGCCGGCGACCUGGGAACUGAUAUCUCGCGCUACUUGACCGACUCUACCGCCCAGUGCAAUGCGAGGCUUCGCUGGCUGAUAAGGAGACCCAUUGAAGCCUGGAAGGCCCAGGAUGGGCCGACGCUCACAACCCUCACCGCAACGCCCCCAUUAUCUUCCAAAACGUUGCUGCAUUCUUCCCAACAAGAAAGACAAACACCGCCAACUACGCAUUUACACUACUGCCUGCCAACUACUGGCAAAGCUUGGCGCAGACGCACUCGGUGGAACCAACGACAAGGCUAUGACAGAGGGGCGUCACUGGCCUCCAAGGAAUUAAUCACUAUACCACCCAGCAAAGUGCACCUCAUACUUAAAAAAGUAGUACUCUCACAUAUUGACCCUCGAUGUCGAUGGCUACUUCACAUUCUACCGUACUCGCACCAGGCUACCUAUAAUCGCAAUGCCAAGCUAGGUGAUCUGAAUGGCGGUCCGUACUAUUCUACGCGCCCCGGAGUAUAUAGGGUCGGCCCGUGUAAUGUGCCGGCAUCAUCUGGAGAACGCACUUGGUUGGACGCAGUGGUCGGCCUCCAAACAGGCCGCCCCCCCAAUCACGGUUUAGUGGGGGCGGCCUCCAACGUCCGCACAAUUACUACUUUUCCCUCGAGCCAGAUUGGAGUACUAUCUCUAAUCCUCUGGCCCACGUCGGCGAAAAAAUCUGUUAUCGACGUCGGGCCCUGCGCCUUGUUUUGCAUUGACACGUAUUAUAUCGCCGGAGUCCCUUGGUUCCGCAUCGCGCUAGAGUGUAGGCUUGGGGAUAGGAGCUAUCCUAUUUCCGUGACCGCACACCAUCAUCUCGUCAUGAAUGAUAGCGUCACUCGGAGGGUCCUAGCGAGGGGAGAAAGAAAAGUAACCCCGGUCCCGCGCCGUACUUCUCACAUGGGCUGUGCUGCCGUGAACAGUGGUCCCGUCUUAGCUGAAACAAGACUAAGCCUCAGUUAUAACUCAUGGACCCGUUACUACCGUCAGCAGCUUUUGCGCCAUUUGAACAGCCGCGUCGUGUGUGGGGUAUUCUCGGCAGGACAUCUACAAUGGCGUGCGGUUCUAUGCUUCGCGCGGGUCGGAGCAAUUAUUUCAACAGCAAAUGCCGACGAGAGCGAUCAGGCGAGCGUCCCAAUACUUGAUCGUGGUAUUAGACAAAGGCAGGGGACAGGCUGGCUAAUUUUGAAGAUCAUCGCACUGCCGCGUACCACGUCAUGCCGGUCGUCAAACACACAACCGCAUUUGUUAGAGGGUGACGGCUAUUCGCAGCCACAUGAACGGACUUCCAUGCUCAGUGUGGGCCGUUCGAAUAACCUUGAGGUGUGUCGACACAUUGGCCCCUCGGUCGUGCGCGUAGUGCGUACUUAUCGAUAUACAGGCGAGAUCGACAUCCGAGUGACCACGGAUCAUGAGCAGGGAGAGCAUAGAGGAUCGGCUAAAAGCCCCCGGUCCCGUAUAUUCGUACAUUUGGCUAAACGGUUGCAGCCUUCGAAGUUAUCGGGAAUAAAUCUGCUCGAUCACGACACUCACGAGAGUAGACUGGUAGUGACAGGUUGGAUGCUGACCUCAAAAAAAAACGAGCCCAGCGCUCAAUUCUACGGCCGCGAGUACUCGCCGCAAUGCGACUACCAUCUAUCUAGUCGACAUGAGGGGAUGACACAAGAAUGCCAGUAUCAGUACCACGCAUACAACCGACCGUAUCGACCACACAGUCGGACUUUCGCAUUACUCAAGAAGGUUUUAGUAGGAGGCUUGACUACAUACUAUCUAAGACGUCUCACGAGCACUACAUGCUGCGGGGGGGGAAACAGGCUCUCGGUGACACGGCGGAACAUUUGCGAAUUACGUCGUGAGGCUCACUGUGGAGGGGGACGGACGAAGUUCAUCUGUCAUAAUACUGAACUUUUAGGGUCGAGUGCCGUGCUUCCUAAAUUCUUUCCUGCAGAGUACCCAAGGAAAGUAUUUAGCAAAGGCGGCCUCCAGAUGGGCGGCGUCUCAACGCCGUCCCACCCCUCCCUUGGUAGAACCUUGGGUCCGCUAUUAAUAGGGGCGGUCCAGAUAUCUCCGCACUUGAAACGGACUCCCGCCAGAAGGCACCGCGUCCUCACACGCCCUUGGGACCUCCAAGCCGGUCUGCUCACGACGAAAUCGGCUACGCAAAUUGGCUCGAGUCAUACGCAUCCCGUAGAAGUAUUGGGCCGGCGUCUUAAAACAUACCGAAACAAGUACGAGCGCUGCGUCCAGCCUAUCGGAGUUGGCAGGGUACGGUUAUAUAAAGGGCCGGAUGCCUUCAGGUAUAUUACGGACGUGCUCGGUCAUCGGUUGGCUUGGCCUUACACUGGUGAAACUACAGGCUCGAAUACUAGUUUCCGUUCUCUUUCAGGACCGGCCGGGGGCCCCUUUAGACGUUCCGAAAACCGACUUAAAGGGCUAUCUAUGGUCUUGGACGCACAGUGCUUCCUCGUCGAUACUUGGAAGCAACCCCCCCACCUGCAUCAAAAGUAUAUCCAGCCGAAGUCCCGGAGAGACUCUGGAGCAUCCCCCACCAUAUCACGUCGAGACCAUAAUUACUCGGACAUCUGUAGGUCCGAGGAAGCGACCAGCCAUGUUAUUGAGAUUCGUCCUCAUGUACUCACUCCUUGCCAUACAAGGACCUUGGUCCGGGUCACGUUAAAUCCUGUACGCUUCGGGCAGAGACUAGUCUACGUAAGACGAGUGAGUCCACCGUCCACAGAGCUAACCGCGAACUUUGAUGCUCCUAAUGAGCCCUCCAUGUCGUCCUUGCGAAUUCUAGGUGACCUAGUACUGGUUAUUUCUAGAAAUGAAGUAUGUGGGAAGGGUGGGAUUGAAACACAUCAAAUGUCUUCUACAGGGCGUUGUUUGCAUCUACUAUCAGGGACCGGCAGGUCUAGAUGCCAACGUUCAUACGGCUCGAGAAGCUUGCAAGCUCCGGCGUUCUCUAUCCGCACUGUGGUGUUACUGAACCGAGAUAUUUGGCUAAGUAUAAAUGACGCCAGCGAUGAGGACCUGCGUCAAGGACUUAACGUACUCAAACUUGCUUGCGUUCUGCCCAUGAUCGUGAAUGAAAAGCUAGGCUCCGUCGUAUCCAAAAACAACGGCCGAGACGCGGUGAAUGACAGUGGACCGACGUCCAUACAGCCUGGUUGCUGGUCUGUUAAGCUUGGUCGAGGGCGUACAGUUUACGCUGGGGCGCGAGGCCCCAGCCGCGAGAAAUGUGUGUUUCUUAGAAGCAGAAGUCGUCACGCUCCUCGGUUGGAUUGCACGAACCUCGUGUCUGUGUGCAGGGACGCAGACGCACAGAUCCACGGGACCUCCAAACUGUGGAUUCUGCGAUAUCUGGGAUUACAUGUUGCGUCCAGUUACCUAGCAGCGACCGGCGGGAAAAUCCCCCGAGUGAGCCGCCCCGCCGCGGCACUGCUUACAUUGUGCGCAGAAAAUGCAAUCGAUAGUAUCACAAGUCGCACGGAGUCCUCAGACCCCACUCAAGUCAAAGCGGGAGCUGAUCUACCAAACAAACAUGGGCCCACGUCAUUUACCGCCAGAAUCCUGGUGAGGAUCUCUUGCAGUUCGCAUGACGGCAAGCGGCGUUGCGCUCGGGAGGAAAUGCUGAAAAGGCUAUUAGCCAGUAUCGCGAUGCGCAAUCUAAAUCACCGGGCACUACUGGGACCUGAACCCAACCCAUUAUGUACGCUUAAUAGAGCACUGCAAAAGGCAGCGGACAUUCAUAUCAAUCGCCUGUAUAUCUUCCUGCGUCAUAGCAAAGGAUCUGUCUCUAGGCGGAGUUCACUGUCAUCGUCGUCAAAGGAAUUCCGUAGUGUCAAGGCCCUUUGUCCGAUGGCAGGACAGAAUAGGUGUGUACAAGACUUACUCACAGGUCUCUUUACGGGGCCCGGGGAAGUCGAUUUCGUCAGCCUGACUCAAGGUUGGAAUCUCAGAUGGCGACCCCGACUCGUGUGGACCGUAGCAAUUCGUCUAAGGCUGCGGUAUGUGGUAGUUUGGGCGUUUAGCCAUGUGUUUAAGCAAACUUGCCCUACUGGAAUCGCGGUGUUCAUGACGAGCCAGUCUUCUAUCCCCGCUUUAACGCGAUUAUGGGGCGAUAGCUUACCCGCACUCAUGAAGAACACAGCUCUCCCCGCUCGGAGCUAUGAUUGCACGGAGCUAGCCUGUCUCGUCCCUCUAACGUACAAGCCGCCUCCUAUCGUUCGCACUCAUCUUCUAAAUGACGGCCCAGUGCAUUAUUUGUCGCGCGCGGGCUUCUACGGUCAAGAGUGCUGUAGUGAAUGUUGCAUUAUCUGGGUAUUGUGUGUGACGUAUUCAAGCCCGAUAACAGAAACCUUUGGAAAAGAGGCACUGUGGUGGCCCUCCAUUACCGGGCUCGAGGUACUCCCAUCUAUGCCUACGGUGUCUGUGCGUGCGUGCAUGCUUACGUGUCCUUUAGAUUGUCUGUAUCCGUCCGUCGAGCUGACAAGAGCGCAAGGCGGAAUCCAUACGAUAAGGACUUACUUAAGCAGUUUUUACCGAGCCUCCCGGACUCGAUGCCCCCCUCGCCACCUCUCCGGGCAAACUUUUGCCAAUCUAGCGGAAGCGAGGAAUUUGGGGGAUAGUGCGGAGAUAGACUUGGUUAUUCCCCUGUUUGAGAAGGACUUUCACCAAUCAGUUUCACGAUUUUCCCUACACACGGUACGGCGCCAUGAAAUUUCCCGCCGGCCCACCGUUCAGCGAGCCAAGACCCGCAAGUCCAAACUCGAGCAGAGUCGCAGUUCUUCGAUAAUGAGCGGCUUCGACACACUUCUCUUGGCCGGAAACCACAGCUACGCAUUACUUGCGACUCACCUGUUAGGGAUUCUGUUAAUGCGCGCCGGUGCCGCUUUCACGCGGAGUUGCCUGACCAAACCGCAGCGAUUCAAAGUAAAUGCGAAUCCCGAGGCCUUGCACUUUAAAUACACCAUCAGACUACGCAACGGAAAAAACGCGUCCCCUUUAUGA'
stop = ('UGA', 'UAA', 'UGA')
F = ('UUU', 'UUC')
L = ('UUA', 'UUG', 'CUU', 'CUC', 'CUA', 'CUG')    
S = ('UCU', 'UCC', 'UCA', 'UCG', 'AGU', 'AGC')
Y = ('UAU', 'UAC')
C = ('UGU', 'UGC')
W = 'UGG'
P = ('CCU', 'CCC', 'CCA', 'CCG')
H = ('CAU', 'CAC')
Q = ('CAA', 'CAG')
R = ('CGU', 'CGC', 'CGA', 'CGG', 'AGA', 'AGG')
I = ('AUU', 'AUC', 'AUA')
M = 'AUG'
T = ('ACU', 'ACC', 'ACA', 'ACG')
N = ('AAU', 'AAC')
K = ('AAA', 'AAG')
S = ('AGU', 'AGC')
V = ('GUU', 'GUC', 'GUA', 'GUG')
A = ('GCU', 'GCC', 'GCA', 'GCG')
D = ('GAU', 'GAC')
E = ('GAA', 'GAG')
G = ('GGU', 'GGC', 'GGA', 'GGG')
RNA_Dict = {F: 'F', L: 'L', S: 'S', Y: 'Y', C: 'C', W: 'W', P: 'P', H: 'H', Q: 'Q', R: 'R', I: 'I', M: 'M', T: 'T', N: 'N', K: 'K', S: 'S', V: 'V', A: 'A', D: 'D', E: 'E', G: 'G', stop: '-'}
RNAList = list(RNA)
print(len(RNA))
triples = []
a = []
b = []
k = ''
for i in range((len(RNAList))):
    if len(a)==3:
        triples.append(a)
        a = []
        a.append(RNAList[i])
    else:
        a.append(RNAList[i])
    if i+1==len(RNAList):
        triples.append(a)
print(len(triples))
for i in range(len(triples)):
    a = ''.join(str(k) for k in triples[i])
    triples[i] = a
for i in range(len(triples)):
    for key, value in RNA_Dict.items():
            if len(key)>1:
                for l in range(len(key)):
                    if triples[i]==key[l]:
                        k = k+value
                        b.append(f'{i} - {len(k)}')
                        break
                    else:
                        print(triples[i], key[l])
                        continue
            if triples[i]==key:
                k = k+value
                b.append(f'{i} - {len(k)}')
                break
            else:
                print(triples[i], key)
                continue
print(k, len(k))
print(b)